// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu5z-HkXr609YufoVfh9l1pFwAytlD73E',
    appId: '1:254957666535:web:d2053f38c2fde58757e242',
    messagingSenderId: '254957666535',
    projectId: 'smarthealthmonitor-8918f',
    authDomain: 'smarthealthmonitor-8918f.firebaseapp.com',
    storageBucket: 'smarthealthmonitor-8918f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuhv5Z8imHIK_Ix-3nOJSYDlURmVZkIB4',
    appId: '1:254957666535:android:cd6c09721221aa1657e242',
    messagingSenderId: '254957666535',
    projectId: 'smarthealthmonitor-8918f',
    storageBucket: 'smarthealthmonitor-8918f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvhNegMg9sqIQ28s6JvFusYXkdytCWhrQ',
    appId: '1:254957666535:ios:8c3c7db4ffba2f8f57e242',
    messagingSenderId: '254957666535',
    projectId: 'smarthealthmonitor-8918f',
    storageBucket: 'smarthealthmonitor-8918f.firebasestorage.app',
    iosBundleId: 'com.example.smarthealtcaremonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvhNegMg9sqIQ28s6JvFusYXkdytCWhrQ',
    appId: '1:254957666535:ios:8c3c7db4ffba2f8f57e242',
    messagingSenderId: '254957666535',
    projectId: 'smarthealthmonitor-8918f',
    storageBucket: 'smarthealthmonitor-8918f.firebasestorage.app',
    iosBundleId: 'com.example.smarthealtcaremonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu5z-HkXr609YufoVfh9l1pFwAytlD73E',
    appId: '1:254957666535:web:ec6798f3f878f7c257e242',
    messagingSenderId: '254957666535',
    projectId: 'smarthealthmonitor-8918f',
    authDomain: 'smarthealthmonitor-8918f.firebaseapp.com',
    storageBucket: 'smarthealthmonitor-8918f.firebasestorage.app',
  );
}
